version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testeusr
      - POSTGRES_PASSWORD=testeusr
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - mynetwork

  demo:
    build:
      context: "./app"
    ports:
      - 8080:8080
    volumes: 
      - "./app/demo/src:/app/src"
    networks:
      - mynetwork
    
networks:
  mynetwork:
