version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testeusr
      - POSTGRES_PASSWORD=testeusr
    volumes: 
      - "./data:/var/lib/postgresql/datas"
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - mynetwork

  demo:
    build:
      context: "./app"
    ports:
      - 8080:8080
    volumes: 
      - "./app/demo/src:/app/src"
    networks:
      - mynetwork

    
  
  #redis:
  #  image: redis
  #  ports:
  #    - "6379:6379"
  #  networks:
  #    - mynetwork
#
  #backend:
  #  build:
  #    context: "./backend"
  #  ports:
  #    - "5000:5000"
  #  networks:
  #    - mynetwork
  #  volumes:
  #    - "./backend:/app"

networks:
  mynetwork:
